### ISSUE TITLE
Can't add the server

### ISSUE THREAD

**Issue by Trylek12** [MrDarkSkil/Launcher_Arma3#10]
http://screencloud.net/v/k0NQ

**Comment by MrDarkSkil** [comment]
Si tu coches la case "Include Subdirectories" tu verras ça marchera 10x mieux ;D

**Comment by Trylek12** [comment]
nope, not work

**Comment by MrDarkSkil** [comment]
What route have you entered in Local Path .
https://gyazo.com/790b9bcc358971c53b3ff25cfd9b30db

**Comment by MrDarkSkil** [comment]
You need to enter "games/{yourServeurNameWithoutSpace}"

**Comment by Trylek12** [comment]
It's work. Thanks for help. I have one more question. What mean "ModDev Enabled" in Launcher in login page. If I try disable this function, Launcher can't connect to my server (404 error in login page)

**Comment by MrDarkSkil** [comment]
You need to create "launcher" folder into the "games" folder.
And upload your launcher (without mod dev) into the launcher folder and rename it "launcher.exe"

**Comment by Trylek12** [comment]
Ok, thank you for help
