### ISSUE TITLE
Comment installer 

### ISSUE THREAD

**Issue by BlayfixScott** [MrDarkSkil/Launcher_Arma3#12]
Avec Wamp ou autre ? comment faire. Car j'arrive a la page d'authentification mais le bouton login est figé

**Comment by MrDarkSkil** [comment]
Ce n'est pas fait pour Wamp, c'est exclusivement fait pour linux.
Tu peux arriver à le mettre en place mais il ne sera pas fonctionnel à 100 %

**Comment by BlayfixScott** [comment]
On peux faire une partie linux sur un dédie windows ?

**Comment by BlayfixScott** [comment]
J'avais pourtant reussi avec un de tes anciennes version du panel ...

**Comment by MrDarkSkil** [comment]
Ouais une partie linux sur windows ça peu le faire, pas le mieux mais ça marchera.

Pour les anciennes versions il n'y avais pas le system multi serveur qui ne marche que sur linux 😄

**Comment by BlayfixScott** [comment]
Tu peux me guider pour la partie linux sur windows ?

**Comment by MrDarkSkil** [comment]
Grâce à https://www.virtualbox.org/, tu crées une VM linux (debian 8) et tu suis le tuto d'installation

**Comment by BlayfixScott** [comment]
daccord mais je dois laisser virtual allumé h24 ?

**Comment by BlayfixScott** [comment]
Tu as un lien pour debian 8 ?

**Comment by BlayfixScott** [comment]
http://www.clubic.com/telecharger-fiche127332-debian.html sa c'est bien ?

**Comment by MrDarkSkil** [comment]
http://cdimage.debian.org/debian-cd/8.6.0/amd64/iso-cd/

**Comment by BlayfixScott** [comment]
J'ai un problème : http://prntscr.com/cv4uqm

**Comment by BlayfixScott** [comment]
Comment mettre la mot de passe ? http://image.prntscr.com/image/60b410f8640e41728107555dcb4ca1d8.png impossible d'ecrire

**Comment by BlayfixScott** [comment]
#1 OK

**Comment by BlayfixScott** [comment]
J'ai tout bien installer maintenant je fait localhost sur le navigateur debian ---> page blanche, et je ne sais pas comment y accéder sans etre sur virtual box

**Comment by BlayfixScott** [comment]
Tu pourras passer ts ce soir si tu as du temps ?

**Comment by BlayfixScott** [comment]
Comment tu mais tes fichier dans le dossier avec le terminal ?

**Comment by BlayfixScott** [comment]
Je peux passer TS ?

**Comment by BlayfixScott** [comment]
FIXER SUR WINDOWS UTILISER XAMPP ;)
