### ISSUE TITLE
bug upload new update

### ISSUE THREAD

**Issue by bozoweed** [MrDarkSkil/Launcher_Arma3#13]
voila alors quand on veut upload la mise ajour du launcher via le panel celui ci repond file size exesed j'ai essayer de changer ça dans le uploader.php mais rien ni fait

**Comment by MrDarkSkil** [comment]
C'est dans la config PHP qu'il faut changer ça 😃

**Comment by bozoweed** [comment]
ok merci :)

**Comment by bozoweed** [comment]
<IfModule mod_php5.c>
  php_value upload_max_filesize 70M
  php_value post_max_size 80M
  php_value memory_limit 90M
  php_value max_execution_time 240
  php_value max_input_time 240
</IfModule> 

ajoute ça a ton .htacces et voila ça marche

**Comment by MrDarkSkil** [comment]
Ajouté 👍

**Comment by bozoweed** [comment]
thanks :)
