### ISSUE TITLE
500 Internal error avec " finish_install.php " 

### ISSUE THREAD

**Issue by Finch29** [MrDarkSkil/Launcher_Arma3#15]
Salut, 
tout est dans le titre :D Comment régler cette erreur ? Merci d'avance

**Comment by MrDarkSkil** [comment]
Manque de permission ?

**Comment by Finch29** [comment]
j'ai tout suivi à la lettre plusieurs fois mais sans succès à ce moment la :( Moment ou il doit créer le compte admin ...

**Comment by Finch29** [comment]
j'ai trouvé, il faut install php5-mcrypt ... qui n'est pas installé par défaut !
