### ISSUE TITLE
Only dev Mod if Work, if False is not work

### ISSUE THREAD

**Issue by FlashModz** [MrDarkSkil/Launcher_Arma3#19]
in your program.cs.
If tested on DevMods enabled, Connect success
If tested on DevMods false, connect not OK

Error on VB : 

Exception thrown: 'System.FormatException' in mscorlib.dll

Screen : 

If desable = http://prntscr.com/d7m48f
If True = http://prntscr.com/d7m51i

Why ? :o

**Comment by bozoweed** [comment]
put the file launcher.exe in games/launcher/ and after that should be work

**Comment by FlashModz** [comment]
Thanks Bozo :p
