### ISSUE TITLE
errore when uptade mod for launcher 4.0.0.0

### ISSUE THREAD

**Issue by bozoweed** [MrDarkSkil/Launcher_Arma3#3]
when we say vmod have change the launcher got a error but we can continue to use it but for fix that you need to delete this line at line 1854 in form1.cs 
....................................................................................;;
 if (version_now != version_up)
                {
                    mods_update = "true";
                    if (!Change_Lang.IsBusy)
                    {           
                        Change_Lang.RunWorkerAsync();
                    }
                    else
                    {
                        System.Threading.Thread.Sleep(500);
                        if (!Change_Lang.IsBusy)
                        {
                            Change_Lang.RunWorkerAsync();
                        }
                    }
                }`

.........................................................................
by this line 

.............................................
if (version_now != version_up)
                {
                    mods_update = "true";
                }
.............................................
sorry if it's not exactly this line the exact line is when the launcher try to run a background work and that give a error
ps: sorry i new in github

**Comment by MrDarkSkil** [comment]
It's corrected with the v 5.0.

**Comment by MrDarkSkil** [comment]
Thanks you for report bug :+1: 
Don't hesitate if you have another error :D
