### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Trylek12** [MrDarkSkil/Launcher_Arma3#4]
Nazwa zdarzenia problemu:	APPCRASH
  Nazwa aplikacji:	LauncherArma3.exe
  Wersja aplikacji:	5.0.0.0
  Sygnatura czasowa aplikacji:	57599337
  Nazwa modułu z błędem:	KERNELBASE.dll
  Wersja modułu z błędem:	6.3.9600.18264
  Sygnatura czasowa modułu z błędem:	56e1b34d
  Kod wyjątku:	e0434352
  Przesunięcie wyjątku:	00015b68
  Wersja systemu operacyjnego:	6.3.9600.2.0.0.272.7
  Identyfikator ustawień regionalnych:	1045
  Dodatkowe informacje 1:	5861
  Dodatkowe informacje 2:	5861822e1919d7c014bbb064c64908b2
  Dodatkowe informacje 3:	1318
  Dodatkowe informacje 4:	13181ae637ac2592fac0ca2dd662cdcc

**Comment by MrDarkSkil** [comment]
What is it ?
Can you give more information about this error, when you see this error ?
