### ISSUE TITLE
Bug trouvé

### ISSUE THREAD

**Issue by crizip** [MrDarkSkil/Launcher_Arma3#5]
Launcher_Arma3/LauncherArma3/LauncherArma3/launcherMain.cs > arma3.exe > arma3battleye.exe

Problème de sauvegarde de login " erreur token " obligé de retaper le compte

**Comment by MrDarkSkil** [comment]
Oui c'est normal, quand tu te connectes sur le panel ça te déconnecte du launcher et ainsi de suite :+1:

**Comment by crizip** [comment]
Sans se connectes au panel juste quand on relance le launcher ^^

**Comment by MrDarkSkil** [comment]
C'est fix dans la prochaine mise à jour :D
