### ISSUE TITLE
Can i use this launcher to my server ?

### ISSUE THREAD

**Issue by Dodaalex2017** [MrDarkSkil/Launcher_Arma3#8]
Hello,
I am owner to server, And i would like if i can use this launcher, and if i can, Where the instruction to edit on launcher , visual basic.
Regards,
Abd-El-Rahman

**Comment by MrDarkSkil** [comment]
You can edit the launcher from Visual Studio and Program.cs file.
You need to change, 

`
/* GENERAL OPTIONS */

string serverName = "Regalian";  /* Your serverName */
string apiUrl = "http://yourserver.com/"; /* Link to API launcher Arma 3 */
`

**Comment by Dodaalex2017** [comment]
Sorry, How can i get a api launcher arma 3 , I searched and i didn't get anything

**Comment by MrDarkSkil** [comment]
Well everything is on GitHub x)
