### ISSUE TITLE
Error Conflit entre 'result'

### ISSUE THREAD

**Issue by Thesam1798** [MrDarkSkil/Launcher_Arma3#9]
Errer lors du test sous VB.net 2013 Pro... je ne connais pas votre application je vous laisse regarder. 
les fichier sont identique que votre GIT.

Avertissement   1  
La variable 'sessionToken' est assignée, mais sa valeur n'est jamais utilisée C:\Users\thesa\Desktop\Launcher_Arma3-master\LauncherArma3\LauncherArma3\Program.cs 36  20  LauncherArma3

Avertissement   2  
Impossible d'atteindre le code détecté    C:\Users\thesa\Desktop\Launcher_Arma3-master\LauncherArma3\LauncherArma3\Themes\Flat UI\FlatListBox.cs  63  5   LauncherArma3

Avertissement   3  
Impossible d'atteindre le code détecté    C:\Users\thesa\Desktop\Launcher_Arma3-master\LauncherArma3\LauncherArma3\Themes\Flat UI\FlatTrackBar.cs 85  5   LauncherArma3

Avertissement   4  
La variable 'tmp' est déclarée, mais jamais utilisée C:\Users\thesa\Desktop\Launcher_Arma3-master\LauncherArma3\LauncherArma3\serverChoose.cs    93  20  LauncherArma3

Avertissement   5  
La variable 'ex' est déclarée, mais jamais utilisée  C:\Users\thesa\Desktop\Launcher_Arma3-master\LauncherArma3\LauncherArma3\Arma3\launcherMain.cs  311 42  LauncherArma3

Avertissement   6  
La variable 'ex' est déclarée, mais jamais utilisée  C:\Users\thesa\Desktop\Launcher_Arma3-master\LauncherArma3\LauncherArma3\Arma3\launcherMain.cs  335 42  LauncherArma3

Avertissement   7  
La variable 'ex' est déclarée, mais jamais utilisée  C:\Users\thesa\Desktop\Launcher_Arma3-master\LauncherArma3\LauncherArma3\Arma3\launcherMain.cs  359 42  LauncherArma3

Avertissement   8  
La variable 'currentUserconfigs' est déclarée, mais jamais utilisée  C:\Users\thesa\Desktop\Launcher_Arma3-master\LauncherArma3\LauncherArma3\Arma3\launcherMain.cs  925 24  LauncherArma3

Avertissement   9  
La variable 'currentSize' est déclarée, mais jamais utilisée C:\Users\thesa\Desktop\Launcher_Arma3-master\LauncherArma3\LauncherArma3\Arma3\launcherMain.cs  930 22  LauncherArma3

> Erreur    10  
> Conflit entre 'result' et la déclaration 'LauncherArma3.launcherMain.result' C:\Users\thesa\Desktop\Launcher_Arma3-master\LauncherArma3\LauncherArma3\Arma3\launcherMain.cs  1090    17  LauncherArma3

Avertissement   11  I
mpossible de lire le fichier d'état "obj\Debug\LauncherArma3.csprojResolveAssemblyReference.cache". Impossible de trouver l'assembly 'Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. LauncherArma3

Avertissement   12  
Impossible de lire le fichier d'état "obj\Debug\LauncherArma3.csproj.GenerateResource.Cache". Impossible de trouver l'assembly 'Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.   LauncherArma3

**Comment by Thesam1798** [comment]
problèmes régler. Merci de fermer

**Comment by MrDarkSkil** [comment]
Normalement il suffit de fermer toutes les vues, compiler le launcher et de réouvrir les vues.
Peux-tu confirmer ?

**Comment by Thesam1798** [comment]
lors de la publication : Erreur	3	Impossible de trouver le certificat de signature de manifeste dans le magasin de certificats.	LauncherArma3

**Comment by Thesam1798** [comment]
en désactivent ClickOnce on a toujours la même errer : Erreur	11	Conflit entre 'result' et la déclaration 'LauncherArma3.launcherMain.result'	C:\Users\thesa\Desktop\Launcher_Arma3-5.1.0.0\LauncherArma3\LauncherArma3\Arma3\launcherMain.cs	1090	17	LauncherArma3

**Comment by LoPix** [comment]
salut, moi perso j'ai sa comme erreur

 L'exception System.NullReferenceException n'a pas été gérée
  HResult=-2147467261
  Message=La référence d'objet n'est pas définie à une instance d'un objet.
  Source=LauncherArma3
  StackTrace:
       à LauncherArma3.loginForm.notifView(String msg) dans C:\Users\Lomaxe\Desktop\Launcher_Arma3-5.1.0.0\LauncherArma3\LauncherArma3\loginForm.cs:ligne 780
       à LauncherArma3.loginForm.loginForm_Load(Object sender, EventArgs e) dans C:\Users\Lomaxe\Desktop\Launcher_Arma3-5.1.0.0\LauncherArma3\LauncherArma3\loginForm.cs:ligne 101
       à System.Windows.Forms.Form.OnLoad(EventArgs e)
       à MetroFramework.Forms.MetroForm.OnLoad(EventArgs e)
       à System.Windows.Forms.Form.OnCreateControl()
       à System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
       à System.Windows.Forms.Control.CreateControl()
       à System.Windows.Forms.Control.WmShowWindow(Message& m)
       à System.Windows.Forms.Control.WndProc(Message& m)
       à System.Windows.Forms.Form.WmShowWindow(Message& m)
       à MetroFramework.Forms.MetroForm.WndProc(Message& m)
       à System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
  InnerException:

**Comment by MrDarkSkil** [comment]
@Thesam1798 as-tu essayé ce que je t'ai dit ?
Tu fermes toutes les vues, tu compiles le launcher et tu réouvres les vues .

**Comment by MrDarkSkil** [comment]
@LoPix et pour toi je vais voir ça tout de suite mais cette erreur me semble bizarre ..

**Comment by Thesam1798** [comment]
@MrDarkSkil oui jais essayer mais rien a faire

**Comment by MrDarkSkil** [comment]
@Thesam1798 ça te fait cette erreur  ?
https://gyazo.com/b234da74836dd4a8996f52fd446be2f4

**Comment by Thesam1798** [comment]
@MrDarkSkil non sa me met juste sa dans la console : Conflit entre 'result' et la déclaration 'LauncherArma3.launcherMain.result' et une errer de premier chance, puis plus rien impossible de continuer

**Comment by MrDarkSkil** [comment]
As-tu des logs exacts ?

**Comment by Thesam1798** [comment]
oui c'est le premier commentaire

**Comment by MrDarkSkil** [comment]
Discord: https://discord.gg/jWq2t

**Comment by LoPix** [comment]
@MrDarkSkil re pour ma part j'ai télécharger ta maj et plus aucuns soucis.  Merci pour ton excellent travaille.

**Comment by LoPix** [comment]
@MrDarkSkil  ha oui j'ai oublier de te dire, il manque le dossier "launcher" dans le dossier "/WebPanel/games/". sinon encore un Grand merci pour ton excellent travaille.

**Comment by MrDarkSkil** [comment]
@LoPix Ah oui c'est exacte, je vais corriger ça ^^

**Comment by MrDarkSkil** [comment]
@Thesam1798 le problème est réglé ?

**Comment by Thesam1798** [comment]
Toujours pas ... Mais je mi remet ce week-end

**Comment by BlayfixScott** [comment]
Visual 2013 net framework 4.5.2 ---> toujours erreur 'result'

**Comment by BlayfixScott** [comment]
Visual 2015 ----> OK

**Comment by BlayfixScott** [comment]
Ok bon, Léo y a quelques truc que je pige pas pour l'installation je passerai ce soir ;)

**Comment by BlayfixScott** [comment]
Thesam1798 il te faut visual Studio 2015 --> ouvrir projet --> (fermer les vues si besoin) --> Demarer (start débug) --> les vue seront accessibles 

_ net framework 4.6
